- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Delete default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Enable and start nginx
  service:
    name: nginx
    state: started
    enabled: true