---
- hosts: lb
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Delete default.conf
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

    - name: Enable nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create server.conf for each server
      template:
        src: server.conf.j2
        dest: /etc/nginx/conf.d/{{ item.server_name }}.conf
      loop:
        - server_port: 7070
          server_name: jmart-ansible.kz
          locations:
            - path: /main
              status_code: 200
              message: Добро пожаловать на JMart!
            - path: /profile
              status_code: 201
              message: Это страница профиля.

        - server_port: 8080
          server_name: jusan-ansible.kz
          locations:
            - path: /
              status_code: 200
              message: Добро пожаловать на Jusan Bank!
            - path: /account
              status_code: 202
              message: Здесь ваш банковский счет!

        - server_port: 9090
          server_name: invest-ansible.kz
          locations:
            - path: /home
              status_code: 200
              message: Добро пожаловать на Jusan Invest!
            - path: /user
              status_code: 203
              message: Это страница с вашим брокерским счетом.
      notify: reload-nginx

  handlers:
    - name: reload-nginx
      service:
        name: nginx
        state: reloaded
