- name: Download the API binary
  get_url:
    url: https://github.com/jusan-singularity/track-devops-systemd-api/releases/download/v0.1/api
    dest: /tmp/api
    mode: 0755

- name: Copy api.service to systemd directory
  copy:
    src: api.service
    dest: /etc/systemd/system/api.service
    mode: '0644'

- name: Reload systemd to register the new service
  systemd:
    daemon_reload: yes

- name: Start and enable the API service
  systemd:
    name: api.service
    state: started
    enabled: yes